/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminTemplatesRouteImport } from './routes/admin.templates'
import { Route as AdminHabitsRouteImport } from './routes/admin.habits'
import { Route as AdminExercisesRouteImport } from './routes/admin.exercises'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AppTodayRouteImport } from './routes/_app.today'
import { Route as AppTeamRouteImport } from './routes/_app.team'
import { Route as AppRecordsRouteImport } from './routes/_app.records'
import { Route as AppQnaRouteImport } from './routes/_app.qna'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPrincipleRouteImport } from './routes/_app.principle'
import { Route as AppLifestyleRouteImport } from './routes/_app.lifestyle'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppHabitsRouteImport } from './routes/_app.habits'
import { Route as AppExercisesRouteImport } from './routes/_app.exercises'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCoachRouteImport } from './routes/_app.coach'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'
import { Route as AppBoardIndexRouteImport } from './routes/_app.board.index'
import { Route as AdminTemplateIdRouteImport } from './routes/admin.template.$id'
import { Route as AppCoachTemplatesRouteImport } from './routes/_app.coach.templates'
import { Route as AppCoachTeamRouteImport } from './routes/_app.coach.team'
import { Route as AppBoardWriteRouteImport } from './routes/_app.board.write'
import { Route as AppBoardPostIdRouteImport } from './routes/_app.board.$postId'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHabitsRoute = AdminHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExercisesRoute = AdminExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AppTodayRoute = AppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppRecordsRoute = AppRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AppRoute,
} as any)
const AppQnaRoute = AppQnaRouteImport.update({
  id: '/qna',
  path: '/qna',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPrincipleRoute = AppPrincipleRouteImport.update({
  id: '/principle',
  path: '/principle',
  getParentRoute: () => AppRoute,
} as any)
const AppLifestyleRoute = AppLifestyleRouteImport.update({
  id: '/lifestyle',
  path: '/lifestyle',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppHabitsRoute = AppHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AppRoute,
} as any)
const AppExercisesRoute = AppExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachRoute = AppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppBoardIndexRoute = AppBoardIndexRouteImport.update({
  id: '/board/',
  path: '/board/',
  getParentRoute: () => AppRoute,
} as any)
const AdminTemplateIdRoute = AdminTemplateIdRouteImport.update({
  id: '/template/$id',
  path: '/template/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AppCoachTemplatesRoute = AppCoachTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppCoachRoute,
} as any)
const AppCoachTeamRoute = AppCoachTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppCoachRoute,
} as any)
const AppBoardWriteRoute = AppBoardWriteRouteImport.update({
  id: '/board/write',
  path: '/board/write',
  getParentRoute: () => AppRoute,
} as any)
const AppBoardPostIdRoute = AppBoardPostIdRouteImport.update({
  id: '/board/$postId',
  path: '/board/$postId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/subscribe': typeof SubscribeRoute
  '/templates': typeof TemplatesRoute
  '/calendar': typeof AppCalendarRoute
  '/coach': typeof AppCoachRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/exercises': typeof AppExercisesRoute
  '/habits': typeof AppHabitsRoute
  '/home': typeof AppHomeRoute
  '/lifestyle': typeof AppLifestyleRoute
  '/principle': typeof AppPrincipleRoute
  '/profile': typeof AppProfileRoute
  '/qna': typeof AppQnaRoute
  '/records': typeof AppRecordsRoute
  '/team': typeof AppTeamRoute
  '/today': typeof AppTodayRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/exercises': typeof AdminExercisesRoute
  '/admin/habits': typeof AdminHabitsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/': typeof AdminIndexRoute
  '/board/$postId': typeof AppBoardPostIdRoute
  '/board/write': typeof AppBoardWriteRoute
  '/coach/team': typeof AppCoachTeamRoute
  '/coach/templates': typeof AppCoachTemplatesRoute
  '/admin/template/$id': typeof AdminTemplateIdRoute
  '/board/': typeof AppBoardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/subscribe': typeof SubscribeRoute
  '/templates': typeof TemplatesRoute
  '/calendar': typeof AppCalendarRoute
  '/coach': typeof AppCoachRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/exercises': typeof AppExercisesRoute
  '/habits': typeof AppHabitsRoute
  '/home': typeof AppHomeRoute
  '/lifestyle': typeof AppLifestyleRoute
  '/principle': typeof AppPrincipleRoute
  '/profile': typeof AppProfileRoute
  '/qna': typeof AppQnaRoute
  '/records': typeof AppRecordsRoute
  '/team': typeof AppTeamRoute
  '/today': typeof AppTodayRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/exercises': typeof AdminExercisesRoute
  '/admin/habits': typeof AdminHabitsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin': typeof AdminIndexRoute
  '/board/$postId': typeof AppBoardPostIdRoute
  '/board/write': typeof AppBoardWriteRoute
  '/coach/team': typeof AppCoachTeamRoute
  '/coach/templates': typeof AppCoachTemplatesRoute
  '/admin/template/$id': typeof AdminTemplateIdRoute
  '/board': typeof AppBoardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/subscribe': typeof SubscribeRoute
  '/templates': typeof TemplatesRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/coach': typeof AppCoachRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/exercises': typeof AppExercisesRoute
  '/_app/habits': typeof AppHabitsRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/lifestyle': typeof AppLifestyleRoute
  '/_app/principle': typeof AppPrincipleRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/qna': typeof AppQnaRoute
  '/_app/records': typeof AppRecordsRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/today': typeof AppTodayRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/exercises': typeof AdminExercisesRoute
  '/admin/habits': typeof AdminHabitsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/board/$postId': typeof AppBoardPostIdRoute
  '/_app/board/write': typeof AppBoardWriteRoute
  '/_app/coach/team': typeof AppCoachTeamRoute
  '/_app/coach/templates': typeof AppCoachTemplatesRoute
  '/admin/template/$id': typeof AdminTemplateIdRoute
  '/_app/board/': typeof AppBoardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/subscribe'
    | '/templates'
    | '/calendar'
    | '/coach'
    | '/dashboard'
    | '/exercises'
    | '/habits'
    | '/home'
    | '/lifestyle'
    | '/principle'
    | '/profile'
    | '/qna'
    | '/records'
    | '/team'
    | '/today'
    | '/admin/announcements'
    | '/admin/exercises'
    | '/admin/habits'
    | '/admin/templates'
    | '/admin/'
    | '/board/$postId'
    | '/board/write'
    | '/coach/team'
    | '/coach/templates'
    | '/admin/template/$id'
    | '/board/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/subscribe'
    | '/templates'
    | '/calendar'
    | '/coach'
    | '/dashboard'
    | '/exercises'
    | '/habits'
    | '/home'
    | '/lifestyle'
    | '/principle'
    | '/profile'
    | '/qna'
    | '/records'
    | '/team'
    | '/today'
    | '/admin/announcements'
    | '/admin/exercises'
    | '/admin/habits'
    | '/admin/templates'
    | '/admin'
    | '/board/$postId'
    | '/board/write'
    | '/coach/team'
    | '/coach/templates'
    | '/admin/template/$id'
    | '/board'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/subscribe'
    | '/templates'
    | '/_app/calendar'
    | '/_app/coach'
    | '/_app/dashboard'
    | '/_app/exercises'
    | '/_app/habits'
    | '/_app/home'
    | '/_app/lifestyle'
    | '/_app/principle'
    | '/_app/profile'
    | '/_app/qna'
    | '/_app/records'
    | '/_app/team'
    | '/_app/today'
    | '/admin/announcements'
    | '/admin/exercises'
    | '/admin/habits'
    | '/admin/templates'
    | '/admin/'
    | '/_app/board/$postId'
    | '/_app/board/write'
    | '/_app/coach/team'
    | '/_app/coach/templates'
    | '/admin/template/$id'
    | '/_app/board/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SubscribeRoute: typeof SubscribeRoute
  TemplatesRoute: typeof TemplatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/habits': {
      id: '/admin/habits'
      path: '/habits'
      fullPath: '/admin/habits'
      preLoaderRoute: typeof AdminHabitsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exercises': {
      id: '/admin/exercises'
      path: '/exercises'
      fullPath: '/admin/exercises'
      preLoaderRoute: typeof AdminExercisesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/today': {
      id: '/_app/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AppTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/records': {
      id: '/_app/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof AppRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/qna': {
      id: '/_app/qna'
      path: '/qna'
      fullPath: '/qna'
      preLoaderRoute: typeof AppQnaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/principle': {
      id: '/_app/principle'
      path: '/principle'
      fullPath: '/principle'
      preLoaderRoute: typeof AppPrincipleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lifestyle': {
      id: '/_app/lifestyle'
      path: '/lifestyle'
      fullPath: '/lifestyle'
      preLoaderRoute: typeof AppLifestyleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/habits': {
      id: '/_app/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof AppHabitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exercises': {
      id: '/_app/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof AppExercisesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coach': {
      id: '/_app/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AppCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/board/': {
      id: '/_app/board/'
      path: '/board'
      fullPath: '/board/'
      preLoaderRoute: typeof AppBoardIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/template/$id': {
      id: '/admin/template/$id'
      path: '/template/$id'
      fullPath: '/admin/template/$id'
      preLoaderRoute: typeof AdminTemplateIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/coach/templates': {
      id: '/_app/coach/templates'
      path: '/templates'
      fullPath: '/coach/templates'
      preLoaderRoute: typeof AppCoachTemplatesRouteImport
      parentRoute: typeof AppCoachRoute
    }
    '/_app/coach/team': {
      id: '/_app/coach/team'
      path: '/team'
      fullPath: '/coach/team'
      preLoaderRoute: typeof AppCoachTeamRouteImport
      parentRoute: typeof AppCoachRoute
    }
    '/_app/board/write': {
      id: '/_app/board/write'
      path: '/board/write'
      fullPath: '/board/write'
      preLoaderRoute: typeof AppBoardWriteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/board/$postId': {
      id: '/_app/board/$postId'
      path: '/board/$postId'
      fullPath: '/board/$postId'
      preLoaderRoute: typeof AppBoardPostIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppCoachRouteChildren {
  AppCoachTeamRoute: typeof AppCoachTeamRoute
  AppCoachTemplatesRoute: typeof AppCoachTemplatesRoute
}

const AppCoachRouteChildren: AppCoachRouteChildren = {
  AppCoachTeamRoute: AppCoachTeamRoute,
  AppCoachTemplatesRoute: AppCoachTemplatesRoute,
}

const AppCoachRouteWithChildren = AppCoachRoute._addFileChildren(
  AppCoachRouteChildren,
)

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppCoachRoute: typeof AppCoachRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppExercisesRoute: typeof AppExercisesRoute
  AppHabitsRoute: typeof AppHabitsRoute
  AppHomeRoute: typeof AppHomeRoute
  AppLifestyleRoute: typeof AppLifestyleRoute
  AppPrincipleRoute: typeof AppPrincipleRoute
  AppProfileRoute: typeof AppProfileRoute
  AppQnaRoute: typeof AppQnaRoute
  AppRecordsRoute: typeof AppRecordsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppTodayRoute: typeof AppTodayRoute
  AppBoardPostIdRoute: typeof AppBoardPostIdRoute
  AppBoardWriteRoute: typeof AppBoardWriteRoute
  AppBoardIndexRoute: typeof AppBoardIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppCoachRoute: AppCoachRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppExercisesRoute: AppExercisesRoute,
  AppHabitsRoute: AppHabitsRoute,
  AppHomeRoute: AppHomeRoute,
  AppLifestyleRoute: AppLifestyleRoute,
  AppPrincipleRoute: AppPrincipleRoute,
  AppProfileRoute: AppProfileRoute,
  AppQnaRoute: AppQnaRoute,
  AppRecordsRoute: AppRecordsRoute,
  AppTeamRoute: AppTeamRoute,
  AppTodayRoute: AppTodayRoute,
  AppBoardPostIdRoute: AppBoardPostIdRoute,
  AppBoardWriteRoute: AppBoardWriteRoute,
  AppBoardIndexRoute: AppBoardIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminExercisesRoute: typeof AdminExercisesRoute
  AdminHabitsRoute: typeof AdminHabitsRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminTemplateIdRoute: typeof AdminTemplateIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminExercisesRoute: AdminExercisesRoute,
  AdminHabitsRoute: AdminHabitsRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminTemplateIdRoute: AdminTemplateIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SubscribeRoute: SubscribeRoute,
  TemplatesRoute: TemplatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
